# Generated by Django 4.1 on 2022-08-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('parentezco', models.CharField(max_length=80)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField()),
            ],
        ),
    ]
