# Generated by Django 4.1 on 2022-08-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamiliarApp', '0002_alter_familiar_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
